apiVersion: v1
kind: Service
metadata:
    name: service-cluster-ip
spec: 
    type: ClusterIP
    selector:
        app: capstone
    ports:
        protocol: TCP
        port: 80
        targetPort: 8080