apiVersion: v1
kind: Service
metadta:
    name: service-loadbalancer
spec:
    type: LoadBalancer
    selector:
        app: capstone
    ports:
        - protocal: TCP
          port: 80
          targetPort: 8080 