apiVersion: v1
kind: Service
metadata:
    name: service-loadbalancer
spec:
    type: LoadBalancer
    selector:
        app: capstone
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080 