apiVersion: v1
kind: Service
metadata: 
    name: service-nodeport
spec:
    type: NodePort
    selector: 
        app: capstone
    port:
        - protocol: TCP
          port: 80
          targetPort: 8080
